trigger:
  branches:
    include:
      - main  # Trigger the pipeline on changes to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Latest Ubuntu VM image

variables:
  - group: Group1  # Reference to variable group 'Group1'
  - name: resourceGroupName
    value: 'Vm-Dep-Gp'  # Resource group name
  - name: subnetName
    value: 'mySubnet'  # Example subnet name
  - name: vnetName
    value: 'myVnet'  # Example virtual network name
  - name: roleDefinitionId
    value: 'b24988ac-6180-42a0-ab88-20f7382dd24c'  # Role definition ID for Virtual Machine Contributor
  - name: vmssName
    value: 'myVmss'  # Example VMSS name

jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template to Azure'
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'VMSS-connection'  # Ensure Service Connection matches exactly
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Setting subscription context..."
            az account set --subscription "$(subscriptionId)"
            echo "Deploying ARM Template..."
            az deployment group create \
              --resource-group "$(resourceGroupName)" \
              --template-file arm-temp.json \
              --parameters adminUsername="$(vmUsername)" adminPassword="$(vmPassword)" \
              --parameters roleAssignmentPrincipalId="$(roleAssignmentPrincipalId)" \
              --parameters subscriptionId="$(subscriptionId)" \
              --parameters subnetName="$(subnetName)" \
              --parameters vnetName="$(vnetName)"
        displayName: 'Deploy ARM Template'

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'VMSS-connection'  # Ensure Service Connection matches exactly
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Assigning RBAC role to VMSS..."
            az role assignment create \
              --assignee "$(roleAssignmentPrincipalId)" \
              --role "$(roleDefinitionId)" \
              --scope "/subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.Compute/virtualMachineScaleSets/$(vmssName)"
        displayName: 'Assign RBAC Role to VMSS'
