trigger:
  branches:
    include:
      - main  # Trigger the pipeline on changes to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Latest Ubuntu VM image

variables:
  - group: Group1  # Reference to variable group 'Group1'
  subnetName: 'mySubnet'  # Example subnet name
  vnetName: 'myVnet'  # Example virtual network name
  subscriptionId: '<your-subscription-id>'  # Ensure this variable is set
  vmUsername: '<your-vm-username>'  # Ensure this variable is set
  vmPassword: '<your-vm-password>'  # Ensure this variable is set
  roleAssignmentPrincipalId: '<your-principal-id>'  # Ensure this variable is set
  roleDefinitionId: '<your-role-definition-id>'  # Ensure this variable is set
  vmssName: '<your-vmss-name>'  # Ensure this variable is set

jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template to Azure'
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'VMSS-connection'  # Ensure Service Connection matches exactly
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Setting subscription context..."
            az account set --subscription $(subscriptionId)
            echo "Deploying ARM Template..."
            az deployment group create \
              --resource-group Vm-Dep-Gp \
              --template-file arm-temp.json \
              --parameters adminUsername=$(vmUsername) adminPassword=$(vmPassword) \
              --parameters roleAssignmentPrincipalId=$(roleAssignmentPrincipalId) \
              --parameters subscriptionId=$(subscriptionId) \
              --parameters subnetName=$(subnetName) \
              --parameters vnetName=$(vnetName)
        displayName: 'Deploy ARM Template'

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'VMSS-connection'  # Ensure Service Connection matches exactly
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Assigning RBAC role to VMSS..."
            az role assignment create \
              --assignee $(roleAssignmentPrincipalId) \
              --role $(roleDefinitionId) \
              --scope "/subscriptions/$(subscriptionId)/resourceGroups/Vm-Dep-Gp/providers/Microsoft.Compute/virtualMachineScaleSets/$(vmssName)"
        displayName: 'Assign RBAC Role to VMSS'
