trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Group1
  - name: resourceGroupName
    value: 'Vm-Dep-Gp'
  - name: subnetName
    value: 'mySubnet'
  - name: vnetName
    value: 'myVnet'

jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template to Azure'
    steps:
      - script: |
          echo "DEBUG: Subscription ID: $(subscriptionId)"
          echo "DEBUG: Resource Group Name: $(resourceGroupName)"
          echo "DEBUG: Subnet Name: $(subnetName)"
          echo "DEBUG: VNet Name: $(vnetName)"
        displayName: 'Print Debug Information'

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'VMSS-connection'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Setting subscription context..."
            az account set --subscription "$(subscriptionId)" || exit 1

            echo "Validating ARM Template..."
            az deployment group validate \
              --resource-group "$(resourceGroupName)" \
              --template-file arm-temp.json \
              --parameters adminUsername="$(vmUsername)" \
                          adminPassword="$(vmPassword)" \
                          roleAssignmentPrincipalId="$(roleAssignmentPrincipalId)" \
                          roleDefinitionId="$(roleDefinitionId)" \
                          subscriptionId="$(subscriptionId)" \
                          subnetName="$(subnetName)" \
                          vnetName="$(vnetName)" \
                          vmssName="$(vmssName)" || exit 1

            echo "Deploying ARM Template..."
            az deployment group create \
              --resource-group "$(resourceGroupName)" \
              --template-file arm-temp.json \
              --parameters adminUsername="$(vmUsername)" \
                          adminPassword="$(vmPassword)" \
                          roleAssignmentPrincipalId="$(roleAssignmentPrincipalId)" \
                          roleDefinitionId="$(roleDefinitionId)" \
                          subscriptionId="$(subscriptionId)" \
                          subnetName="$(subnetName)" \
                          vnetName="$(vnetName)" \
                          vmssName="$(vmssName)" || exit 1
        displayName: 'Deploy ARM Template'
