trigger:
  branches:
    include:
      - main  # Trigger the pipeline when changes are pushed to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Using the latest Ubuntu VM image to run the pipeline

variables:
  - group: Group1  # Reference to the variable group 'Group1'
  # Ensure these variables are correctly referenced in Group1 or added here

jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template to Azure'
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'Zubin''s Sub'  # Ensure Service Connection is correctly set
          scriptType: 'bash'  # Use bash for scripting
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Setting subscription context..."
            # Check if subscriptionId is set
            if [ -z "$(subscriptionId)" ]; then
              echo "Error: subscriptionId is not set."
              exit 1
            fi
            az account set --subscription $(subscriptionId)  # Set the subscription context dynamically
            echo "Deploying ARM Template..."
            az deployment group create \
              --resource-group Vm-Dep-Gp \
              --template-file arm-temp.json \
              --parameters adminUsername=$(vmUsername) adminPassword=$(vmPassword)
        displayName: 'Deploy ARM Template'

      - task: AzureCLI@2
        inputs:
          azureSubscription: 'Zubin''s Sub'  # Ensure Service Connection is correctly set
          scriptType: 'bash'  # Use bash for scripting
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Checking if roleAssignmentPrincipalId is set..."
            # Check if roleAssignmentPrincipalId is set
            if [ -z "$(roleAssignmentPrincipalId)" ]; then
              echo "Error: roleAssignmentPrincipalId is not set."
              exit 1
            fi
            echo "Assigning RBAC role to VMSS..."
            az role assignment create \
              --assignee $(roleAssignmentPrincipalId) \
              --role $(roleDefinitionId) \
              --scope "/subscriptions/$(subscriptionId)/resourceGroups/Vm-Dap-Gp/providers/Microsoft.Compute/virtualMachineScaleSets/$(vmssName)"
        displayName: 'Assign RBAC Role to VMSS'
