trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Group1  # Reference the variable group containing predefined variables
  - name: subnetName
    value: 'mySubnet'
  - name: vnetName
    value: 'myVnet'
  - name: system.debug
    value: 'true'  # Enable debug logs

jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template to Azure'
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'VMSS-connection'  # Azure DevOps Service connection
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            set -e # Exit on any command failure

            echo "##vso[task.debug]Enabling debug logs..."
            echo "Setting subscription context..."
            az account set --subscription "$(subscriptionId)"

            # Validate ARM Template
            echo "Validating ARM Template..."
            az deployment group validate \
              --resource-group "$(resourceGroupName)" \
              --template-file arm-temp.json \
              --parameters \
              adminUsername="$(vmUsername)" \
              adminPassword="$(vmPassword)" \
              roleAssignmentPrincipalId="$(roleAssignmentPrincipalId)" \
              roleDefinitionId="$(roleDefinitionId)" \
              subscriptionId="$(subscriptionId)" \
              subnetName="$(subnetName)" \
              vnetName="$(vnetName)" \
              vmssName="$(vmssName)" \
              resourceGroupName="$(resourceGroupName)" \
              --verbose 

            # Deploy ARM Template
            echo "Deploying ARM Template..."
            az deployment group create \
              --resource-group "$(resourceGroupName)" \
              --template-file arm-temp.json \
              --parameters \
              adminUsername="$(vmUsername)" \
              adminPassword="$(vmPassword)" \
              roleAssignmentPrincipalId="$(roleAssignmentPrincipalId)" \
              roleDefinitionId="$(roleDefinitionId)" \
              subscriptionId="$(subscriptionId)" \
              subnetName="$(subnetName)" \
              vnetName="$(vnetName)" \
              vmssName="$(vmssName)" \
              resourceGroupName="$(resourceGroupName)" \
              --verbose 
        displayName: 'Deploy ARM Template'