trigger:
  branches:
    include:
      - main  # Trigger pipeline on changes to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Group1  # Reference your variable group containing predefined variables
  - name: resourceGroupName
    value: 'Vm-Dep-Gp'  # Resource group name
  - name: subnetName
    value: 'mySubnet'  # Subnet name
  - name: vnetName
    value: 'myVnet'  # Virtual network name

jobs:
  - job: DeployARMTemplate
    displayName: 'Deploy ARM Template to Azure'
    steps:
      # Step 1: Deploy ARM Template
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'VMSS-connection'  # Azure service connection
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Setting subscription context..."
            az account set --subscription $(subscriptionId)
            echo "Deploying ARM Template..."
            az deployment group create \
              --resource-group $(resourceGroupName) \
              --template-file arm-temp.json \
              --parameters adminUsername=$(vmUsername) \
                          adminPassword=$(vmPassword) \
                          roleAssignmentPrincipalId=$(roleAssignmentPrincipalId) \
                          roleDefinitionId=$(roleDefinitionId) \
                          subscriptionId=$(subscriptionId) \
                          subnetName=$(subnetName) \
                          vnetName=$(vnetName) \
                          vmssName=$(vmssName)
        displayName: 'Deploy ARM Template'

      # Step 2: Assign RBAC Role to VMSS
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'VMSS-connection'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            echo "Assigning RBAC role to VMSS..."
            az role assignment create \
              --assignee $(roleAssignmentPrincipalId) \
              --role $(roleDefinitionId) \
              --scope "/subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.Compute/virtualMachineScaleSets/$(vmssName)"
        displayName: 'Assign RBAC Role to VMSS'
